services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongodb-init:
    image: mongo:8.0
    container_name: mongodb-init
    depends_on:
      - mongodb
    volumes:
      - ./mongodb-init:/init
    entrypoint: ["mongosh", "mongodb://mongodb:27017/dexterity", "/init/seed-incidents-testdata.js", "/init/seed-tasks-testdata.js", "/init/seed-wiki-testdata.js"]

  signon:
    image: quay.io/keycloak/keycloak
    container_name: keycloaksignon
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev

  shell:
    build:
      context: shell
    image: rarelyprolific/dexterity-shell:latest
    container_name: dexterity-shell

volumes:
  mongo_data:
