services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  signon:
    image: quay.io/keycloak/keycloak
    container_name: signon
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev

  shell:
    build:
      context: shell

volumes:
  mongo_data:
