{{- range .Values.apis }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        env:
        - name: MONGODB_URI
          value: "mongodb://{{ $.Release.Name }}-mongodb.default.svc.cluster.local:27017"
---
{{- end }}
