apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: rarelyprolific/dexterity-shell:latest
