apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: rarelyprolific/dexterity-shell:latest
        env:
        - name: INCIDENT_API_URI
          value: "http://{{ $.Release.Name }}-incidentapi.default.svc.cluster.local"
        - name: TASK_API_URI
          value: "http://{{ $.Release.Name }}-taskapi.default.svc.cluster.local"
